### ISSUE TITLE
About Sass

### ISSUE THREAD

**Issue by i12n** [gewenmao/gewenmao.github.io#2]
## Sass Mixins

Mixins support us to reuse a group of CSS declarations.

``` scss
// SCSS
@mixin bg($icon){
    background-img:url($icon);
}

.error {
    @include bg('error.png');
}
.cancel {
    @include bg('cancel.png');
}
```

``` css
/* Output CSS */
.error {
  background-img: url("error.png");
 }

.cancel {
  background-img: url("cancel.png"); 
}
```
