### ISSUE TITLE
About CSS

### ISSUE THREAD

**Issue by i12n** [gewenmao/gewenmao.github.io#3]
## Negative Margin

![image](http://gewenmao.github.io/assets/images/web/css/Negative-Margin-Header-20150930.png)
-  `header` in horizontal center of container
-  `more` link at right of  container
-  the bottoms of `header` and `more` are align 

Set   `more`  float right and move it up with negative margin.
 [Example](https://jsbin.com/vacinu/2/edit?html,css,output)

**Comment by i12n** [comment]
## CSS3 Gradient

### Zig Zag

![image](http://gewenmao.github.io/assets/images/web/css/Zig-Zag-20150930.png)

Use css3 linear-gradient set background

[Example](https://jsbin.com/gufavu/2/edit?html,css,output)

**Comment by i12n** [comment]
## Missing Corner(Dog Ear)

![image](http://gewenmao.github.io/assets/images/web/css/Missing-Corner-20151013.png)

Set a triangle by border and cover the corner of box.

[Example](https://jsbin.com/kayesi/2/edit?html,css,output)

In addition, css3 _line-gradient_ can do the same thing.  

[Example](https://jsbin.com/seladiq/2/edit?html,css,output)

**Comment by i12n** [comment]
## Tag Style

![image](http://gewenmao.github.io/assets/images/web/css/Tag-Style-20151020.png)

Make triangle by ::after and ::before.
[Example](https://jsbin.com/kakaqi/3/edit?html,css,output)

**Comment by i12n** [comment]
## Album Cover Mask

![image](http://gewenmao.github.io/assets/images/web/css/Album-Cover-Mask-20151021.png)
- Positioning method:  `absolute`
- Selectors based on relationships: `>`
- Transparent method: `rgba` or `opacity`

[Example](https://jsbin.com/someci/2/edit?html,css,output)

**Comment by i12n** [comment]
## Rate Star

![image](http://gewenmao.github.io/assets/images/web/css/Rate-Star-20151114.png)

Two `span`, the outer  `span` has a fixed width and its background is a gay star image; the width of the inner `span` is variable based on inline-style and its background is an orange star image.

[Example](https://jsbin.com/kadusu/2/edit?html,css,output)

**Comment by i12n** [comment]
## Div Border Collapse

The first method, set  one of the contacting borders' `width = 0`.
[Example](https://jsbin.com/nevaki/2/edit?html,css,output)

The second method, the out and inner div's `display` can be set `table` and `table-cell`, then `border-collapse` can be used.
[Example](https://jsbin.com/lijaju/2/edit?html,css,output)

The third method, not set `border` but set `box-shadow`. This is an interest method, we can get more detail thing about it in [here](http://codepen.io/Hawkun/pen/rsIEp).
[Example](https://jsbin.com/xaweze/1/edit?html,css,output)

**Comment by i12n** [comment]
## PingFangSC-Regular & font-smoothing

``` html
<style>
html {
    font-family: PingFangSC-Regular,'Source Sans Pro','Lucida Grande',sans-serif;
}
</style>
```

Maybe the font seem to be a little bord, using font-smoothing fix it.

``` html
<style>
html {
    font-family: PingFangSC-Regular,'Source Sans Pro','Lucida Grande',sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
</style>
```

**Comment by i12n** [comment]
## |

```
<p>ID<span style="border-left:2px solid; margin-left: 12px;padding: 10px 6px 1px;font-size: 0;"></span>Email</p>
```

If we use `|`, we can't control its height.

**Comment by i12n** [comment]
## get a square  by `padding`

`<div style="padding:50%;background:#999;"></div>`

**Comment by i12n** [comment]
# img set width & height

```
<img src="xxx" />
```

在 `<img>` 标签中如果不设置长宽属性，在Android机器上会出现变大的现象；而在iPhone则显示正常。

例如：
![](http://gewenmao.github.io/assets/images/web/css/set-image-size.png)

为了避免这种情况发生，需要设置width和height

``` css
img {
    width: 1.6rem;
    height: 1rem;
}
```

**Comment by i12n** [comment]
# Remove  space inline-block space between elements

在做响应式布局时，常常需要等百分比来设置with，例如：

``` html
<ul>
    <li>A</li>
    <li>B</li>
    <li>C</li>
    <li>D</li>
</ul>
```

``` css
ul {
      display: block;
      width: 100%;
      position: relative;
}
ul li {
     display: inline-block;
     width: 25%;
}
```

每个 `<li>` 的width为`<ul>`的1/4，因为在   inline-block 元素之间会有一个空白缝隙，导致`<ul>`不能完全放得下四个 `<li>`.

可以参照  [fighting-the-space-between-inline-block-elements](https://css-tricks.com/fighting-the-space-between-inline-block-elements/)提出的几种方法进行处理。
值得注意的是，如果 使用的是 font-size: 0; 那么在一些 Android 机器上的 APP 中浏览页面时，还是会出现那个空白缝隙，也就是没有起作用。这个时候使用下面的方式则不会在 Android 机器 出现问题：

``` html
<ul>
      <li>
      A</li><li>
      B</li><li>
      C</li><li>
      D</li>
</ul>
```

**Comment by i12n** [comment]
## 更改 checkbox 样式

``` html
<div>
  <input type="checkbox" id="check-input"/>
  <label for="check-input">已经阅读该协议 </label>
</div>
```

``` css
input[type=checkbox] {
    display: inline-block;
    width: 0;
    height: 0;
    outline: 0;
    -webkit-appearance: none;
    visibility: hidden;
}


input[type=checkbox]:after {
    content: " ";
    width: .38rem;
    height: .38rem;
    display: inline-block;
    visibility: visible;
    vertical-align: top;

    background-image: url('xxx.png');
    background-size: cover;
    background-position: center center;

}

input[type=checkbox]:checked:after {
    content: " ";
    background-image: url('xxxx.png');
    width: .38rem;
    height: .38rem;
    background-size: cover;
    background-position: center center;
}

label {
    margin-left: -.02rem;
    padding-left: .5rem;
    height: .38rem;
    line-height: .38rem;
    display: inline-block;
    vertical-align: top;
    font-size: .28rem;
    color: #666666;
}
```

关键点：
1.用 ::after 来实现 checkbox 效果，checkbox 隐藏
2. checkbox 虽然长宽都已经为 0 ，但是还要 设置 hidden，因为在 iphone 会出现一个点
3. label 的 for 属性与 checkbox 关联，这样点击 label 可以触发checkbox，将label区域覆盖 checkbox:after 区域
4. 背景图片要用 `background-size: cover;` 和  `background-position: center center;` 否则在 Android 上适配会出现问题。
5. `vertical-align: top;` 也是为了适配 Android

**Comment by i12n** [comment]
## flex 实现简单的左右布局

```html
<div class="container">
  <p class="left">示例代码</p>
  <a class="right" href="#">点击查看</a>
</div>
```

```css
.container {
  display: flex;
}
.left {
  flex: 1;
}
```
[代码示例](https://jsfiddle.net/moonatcs/om6r44as/)

**Comment by i12n** [comment]
## 通过 border 实现箭头 `>` 方法

```html
<a href="#">点击链接</a>
```
```css
a {
  color: #b0b0b0;
  text-decoration: none;
}

a::after {
  content: '';
  display: inline-block;
  position: relative;
  width: 8px;
  height: 8px;
  border-left: 2px solid #b0b0b0;
  border-bottom: 2px solid #b0b0b0;
  transform: scaleX(0.7) rotateZ(-135deg);
}
```
[示例代码](https://jsfiddle.net/moonatcs/9godk8vp/)

**Comment by i12n** [comment]
## flex 实现一个简单 tab 样式
```html
<ul class="list">
  <li class="item"><span>Food</span></li>
  <li class="item item-active"><span>Book</span></li>
  <li class="item"><span>Movie</span></li>
</ul>
```

```css
.list {
  display: flex;
  margin: 0;
  padding: 0;
  height: 30px;
  border-bottom: 1px #B0B0B0 solid;
}

.item {
  flex: 1;
  position: relative;
  line-height: 30px;
  list-style: none;
}

.item span {
  display: block;
  text-align: center;
}

.item-active span {
  color: #f18c16;
}

.item-active::after {
  content: '';
  position: absolute;
  width: 100%;
  height: 0;
  bottom: -2px;
  border-bottom: 3px #f18c16 solid;
}
```

[代码示例](https://jsfiddle.net/moonatcs/gdc507vk/)

**Comment by i12n** [comment]
## display:flex 与 display:-webkit-box 

两者的区别如下：
1. `display:flex` 在某些Android机器上不支持，而 `display:-webkit-box `在某些浏览器（如 火狐）不支持。为了适配的好一些，可以把两者都写上
2.  `display:flex` 对应项目的伸缩属性为 flex，默认值为 `flex:0 1 auto` 即项目元素在主轴方向不可伸长、可以缩短；而  `display:-webkit-box ` 对应项目的伸缩属性为 -webkit-box-flex，默认值为  `-webkit-box-flex:0` ，表示项目元素在主轴方向既不能伸长也不能缩短

```html
<!-- 文字过长被隐藏 -->
<p class="webkit-box">
  <span class="title"> -webkit-box 布局示例：文字隐藏</span>
  <span class="tag">hot</span>
</p>

<!-- 文字太短间距太大 -->
<p class="webkit-box">
  <span class="title"> -webkit-box 示例</span>
  <span class="tag">hot</span>
</p>

<!-- 额外的元素占位 -->
<p class="webkit-box">
  <span class="title"> -webkit-box</span>
  <span class="tag">hot</span>
  <span class="fill"></span>
</p>

<!-- 文字过长被隐藏 -->
<p class="flex-box">
  <span class="title">css flex 布局示例样式：文字隐藏</span>
  <span class="tag">hot</span>
  <span class="fill"></span>
</p>

<!-- 文字太短 -->
<p class="flex-box">
  <span class="title">css flex 示例</span>
  <span class="tag">hot</span>
</p>
```

```css
.webkit-box {
  display: -webkit-box;
  width: 300px;
  font-size: 20px;
}
.flex-box {
  display: flex;
  width: 300px;
  font-size: 20px;
}
.title {
  display: block;
  vertical-align: middle;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.tag {
  display: block;
  background: #e95200;
  font-size: 18px;
  color: #fff;
  vertical-align: middle;
  text-align: center;
  line-height: 20px;
}

.webkit-box .title {
  -webkit-box-flex: 1;
}

.webkit-box .fill {
  display: block;
  -webkit-box-flex: 20;
}
.flex-box .title {
  flex: 0 1 auto;
}
```
[代码示例](https://jsfiddle.net/moonatcs/gn9pyo5k/1/)

[https://css-tricks.com/snippets/css/a-guide-to-flexbox/](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
